name: list created node_modules and delete

on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install PHP Dependecies
        run: |
          composer install -o
          npm install
      - name : NPM Build
        run: npm run build
      - name: Show files
        run: 'ls -a'
      - name: Show files after node_modules deleted via rm
        run: | 
            rm -R "node_modules/"
            ls -a

